apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
data:
  policy.default: role:readonly
  policy.csv: |
    p, role:sysadmin, applications, *, */*, allow
    p, role:sysadmin, clusters, get, *, allow
    p, role:sysadmin, repositories, get, *, allow
    p, role:sysadmin, repositories, create, *, allow
    p, role:sysadmin, repositories, update, *, allow
    p, role:sysadmin, repositories, delete, *, allow
    p, role:image-updater, applications, get, */*, allow
    p, role:image-updater, applications, update, */*, allow
    g, image-updater, role:image-updater
    g, george, role:sysadmin
