---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cloud-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure applications with respect to clouds.
  sourceRepos:
  - '*'
  destinations:
  - namespace: 'crossplane-system'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false
