apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd
  newTag: 2.3.0-c078bbb5

resources:
- base/argocd-namespace.yaml
- base/rollouts-extension.yaml
- base/argocd-image-updater-install.yaml
- base/argocd-projects.yaml
- base/argocd-applications.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- overlays/production/argocd-cm.yaml
- overlays/production/argocd-rbac-cm.yaml
- overlays/production/argocd-notifications-v1.2.1-install.yaml
- overlays/production/argocd-notifications-catalog-v1.2.1-install.yaml
