apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- base/argocd-namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
- https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/master/manifests/install.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- base/config/argocd-cm.yaml
- base/config/argocd-rbac-cm.yaml
- base/config/argocd-notifications-cm.yaml
