apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gcp-projects
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/tsungchih/crossplane-demo.git
      revision: HEAD
      directories:
      - path: gcp/projects/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: cloud-infra
      source:
        repoURL: https://github.com/tsungchih/crossplane-demo.git
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: true
          jsonnet: {}
      destination:
        server: https://kubernetes.default.svc
        namespace: crossplane-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
