apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: argo
  generateName: hello-world-
spec:
  entrypoint: sayHello
  templates:
    - name: sayHello
      container:
        image: alpine:latest
        command: [ echo ]
        args: [ "hello world" ]