apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 3.33.5
    repository: https://argoproj.github.io/argo-helm
  - name: argocd-applicationset
    version: 1.9.1
    repository: https://argoproj.github.io/argo-helm