argo-cd:
  installCRDs: false
  global:
    image:
      tag: v2.2.5
  controller:
    # -- Deploy the application controller as a StatefulSet instead of a Deployment, this is required for HA capability.
    # This is a feature flag that will become the default in chart version 3.x
    #enableStatefulSet: true
    # -- Application controller log format. Either `text` or `json`
    logFormat: text
    # -- Application controller log level
    logLevel: info
  ## Deploy the Redis with HA support, this is required for HA capability.
  #redis-ha:
  #  enabled: true
  ## Deploy the RepoServer with HA support, this is required for HA capability.
  #repoServer:
  #  autoscaling:
  #    enabled: true
  #    minReplicas: 2

  ## ArgoCD configuration
  ## Ref: https://github.com/argoproj/argo-cd
  ##
  ## Server
  server:
    ## To deploy Argo CD with HA support, we have to uncomment one of the 
    ## following configuration section depending on whether autoscaling 
    ## feature is concerned.
    ## HA mode with autoscaling
    #autoscaling:
    #  enabled: true
    #  minReplicas: 2
    ## HA mode without autoscaling
    #replicas: 2
    #env:
    #  - name: ARGOCD_API_SERVER_REPLICAS
    #    value: '2'
    configEnabled: true
    config:
      repositories: |
        - type: git
          url: https://github.com/tsungchih/argocd-demo.git
        - name: argo-helm
          type: helm
          url: https://argoproj.github.io/argo-helm
    additionalApplications: 
      - name: argocd
        namespace: argocd
        destination:
          namespace: argocd
          server: https://kubernetes.default.svc
        project: argocd
        source:
          helm:
            version: v3
            valueFiles:
            - values.yaml
          path: helm/argo-cd
          repoURL: https://github.com/tsungchih/argocd-ex.git
          targetRevision: HEAD
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
    additionalProjects: 
    - name: argocd
      namespace: argocd
      additionalLabels: {}
      additionalAnnotations: {}
      description: Argocd Project
      sourceRepos:
      - '*'
      destinations:
      - namespace: argocd
        server: https://kubernetes.default.svc
      clusterResourceWhitelist:
      - group: '*'
        kind: '*'
      orphanedResources:
        warn: false

